// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TenantForge.Modules.Iam.Infrastructure;

#nullable disable

namespace TenantForge.Modules.Iam.infrastructure.Migrations
{
    [DbContext(typeof(IamDbContext))]
    [Migration("20260912183000_NormalizeTenantPermissionKeys")]
    partial class NormalizeTenantPermissionKeys
    {
    }
}
