// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantForge.Modules.Shop.Infrastructure;

#nullable disable

namespace TenantForge.Modules.Shop.infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260923163122_AddShopPaymentLifecycle")]
    partial class AddShopPaymentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCart", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("LastTouchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_touched_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_shop_carts_status_expires_at_utc");

                    b.ToTable("shop_carts", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCartItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_cart_items_cart_variant");

                    b.ToTable("shop_cart_items", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_categories_tenant_slug");

                    b.HasIndex("TenantId", "ParentCategoryId", "DisplayOrder")
                        .HasDatabaseName("ix_shop_categories_tenant_parent_display_order");

                    b.ToTable("shop_categories", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCoupon", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaximumDiscountAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("maximum_discount_amount");

                    b.Property<decimal>("MinimumSubtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("minimum_subtotal");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_code");

                    b.Property<int>("RedeemedCount")
                        .HasColumnType("integer")
                        .HasColumnName("redeemed_count");

                    b.Property<int?>("RedemptionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("redemption_limit");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_coupons_tenant_normalized_code");

                    b.ToTable("shop_coupons", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTimeOffset?>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at_utc");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("grand_total");

                    b.Property<DateTimeOffset?>("InventoryReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inventory_released_at_utc");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_number");

                    b.Property<string>("ShippingAddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("shipping_address_line");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("shipping_city");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipping_postal_code");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("shipping_province");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sub_total");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tracking_code");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_orders_order_number");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_orders_tracking_code");

                    b.HasIndex("TenantId", "TrackingCode", "CustomerPhone")
                        .HasDatabaseName("ix_shop_orders_tenant_tracking_phone");

                    b.ToTable("shop_orders", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("VariantLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("variant_label_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shop_order_items_order_id");

                    b.ToTable("shop_order_items", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopOrderOperation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("ResponseSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_snapshot");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shop_order_operations_order_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_order_operations_tenant_idempotency_key");

                    b.ToTable("shop_order_operations", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopPaymentAttempt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_snapshot");

                    b.Property<DateTimeOffset?>("CallbackReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("callback_received_at_utc");

                    b.Property<string>("CallbackTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("callback_token_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("failure_code");

                    b.Property<string>("GatewayReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("gateway_reference");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GatewayReference")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_payment_attempts_gateway_reference");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shop_payment_attempts_order_id");

                    b.ToTable("shop_payment_attempts", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopPaymentInitiation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("redirect_url");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("TokenSeed")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_seed");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shop_payment_initiations_order_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_payment_initiations_tenant_idempotency_key");

                    b.ToTable("shop_payment_initiations", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("compare_at_price");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("GalleryVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("gallery_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_shop_products_category_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_products_tenant_slug");

                    b.ToTable("shop_products", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProductImage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("storage_key");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_shop_product_images_storage_key");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_shop_product_images_product_display_order");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_shop_product_images_tenant_product");

                    b.ToTable("shop_product_images", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("color");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_override");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sku");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Color", "Size")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_product_variants_product_color_size");

                    b.ToTable("shop_product_variants", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AboutText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("about_text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("instagram_url");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentPolicy")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)")
                        .HasColumnName("payment_policy");

                    b.Property<string>("PrivacyPolicy")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)")
                        .HasColumnName("privacy_policy");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)")
                        .HasColumnName("return_policy");

                    b.Property<string>("ShippingPolicy")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)")
                        .HasColumnName("shipping_policy");

                    b.Property<string>("SupportPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("support_phone");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("tagline");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_profiles_tenant_id");

                    b.ToTable("shop_profiles", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopShippingRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("province_name");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProvinceName")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_shipping_rates_tenant_province");

                    b.ToTable("shop_shipping_rates", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideCell", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ColumnId")
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    b.Property<long>("RowId")
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RowId", "ColumnId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_size_guide_cells_row_column");

                    b.ToTable("shop_size_guide_cells", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideColumn", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_shop_size_guide_columns_product_id");

                    b.ToTable("shop_size_guide_columns", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("SizeLabel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("size_label");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_shop_size_guide_rows_product_id");

                    b.ToTable("shop_size_guide_rows", (string)null);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCartItem", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopCart", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopCategory", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopOrderItem", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopOrderOperation", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopPaymentAttempt", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopPaymentInitiation", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProduct", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProductImage", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopProductVariant", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideCell", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopSizeGuideColumn", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopSizeGuideRow", null)
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideColumn", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantForge.Modules.Shop.Domain.ShopSizeGuideRow", b =>
                {
                    b.HasOne("TenantForge.Modules.Shop.Domain.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
